### PR TITLE
AOSP 4.2.2

### PR DESCRIPTION
**Pull request by luki122**

### CODE REVIEW

**Comment by msfjarvis** [comment]
server down

**Comment by RememberTheAir** [comment]
@MSF-Jarvis Typing random commands in the console works

**Comment by regalstreak** [comment]
huh?
 @RememberTheAir

**Comment by msfjarvis** [comment]
@regalstreak Brain dead guy apparently

**Comment by RememberTheAir** [comment]
@MSF-Jarvis @regalstreak I'm sorry for that comment, it looks like a bug of the Telegram bot [@GitHubBot](telegram.me/githubbot).

I've searched in my history for *"Typing random commands in the console works"* (screenshot [here](http://i.imgur.com/r1bt1dk.png), the conversation dates back to 25th October) and apparently the bot posted my message under this pull request.

@MSF-Jarvis are you using that bot too? I'm pretty sure I've seen your propic somewhere on Telegram

**Pull request closed without merging**
