### PR TITLE
Compress cm-14.1 Sources

### PR DESCRIPTION
**Pull request by ShadowReaper1**
Compress and upload both repo and nonrepo folders.

### CODE REVIEW

**Comment by msfjarvis** [comment]
@ShadowReaper1 Server ded, we lazy

**Comment by ShadowReaper1** [comment]
hahaha

**Comment by NazarMohamed** [comment]
@MSF-Jarvis When you will repair it

**Comment by msfjarvis** [comment]
@NazarMohamed Can't find my tools..... Going to check in the shed tomorrow, festival today

**Comment by NazarMohamed** [comment]
@MSF-Jarvis You guys are doing good things to us.Please Repair it soon.

**Comment by regalstreak** [comment]
Server and the skadoosh project are live again, please submit again after resolving conflicts. Thanks!

**Pull request closed without merging**
