### PR TITLE
Add XOS-N source code

### PR DESCRIPTION
**Pull request by rokibhasansagar**
The **XOS** official source code for "**Infinix Hot 4 Pro**" based on Android Nougat

### CODE REVIEW

**Comment by regalstreak** [comment]
XOS is halogenOS
halogenos.org
github.com/halogenos

**Comment by rokibhasansagar** [comment]
Sorry, but I searched a little about it.
My commit was for infini**xOS**, named "**XOS Chameleon**", I mistakenly wrote only the short form. 
It's an Updated version of **XUI** from the same company.

The _**halogenOS XOS**_ is Not the same. And they are built for many **Qualcomm-based** chipset.
But the XOS Chameleon is only built for **MediaTek-based Infinix Mobiles**.

Hence, the ROM name written by me should be corrected as "XOS-chameleon-N" or "**InfinixOS**".

If you are interested, details can be found [Here](http://www.infinixmobility.com/xos/overview/)

**Comment by msfjarvis** [comment]
@rokibhasansagar

**Comment by regalstreak** [comment]
Write infinixOS and resubmit

**Pull request closed without merging**
