### PR TITLE
CyanogenMod 11.0

### PR DESCRIPTION
**Pull request by ItsAnilSingh**
Can we have CyanogenMod 11.0 highly compresses source please? The older links are outdated one.

### CODE REVIEW

**Comment by msfjarvis** [comment]
We are not accepting pull requests for a while.

**Comment by regalstreak** [comment]
@itsanilsingh for the timebeing wait. I had hacked up the script for cm-14.0 I'll do this when im back

**Comment by regalstreak** [comment]
Sorry for the mess, there was a mess up on the server due to the current shit we had 
All is fine now and it is compressing

**Comment by ItsAnilSingh** [comment]
Dont be sorry bro.. you are doing a lot for us.. take ur own time..

**Comment by regalstreak** [comment]
these were up

**Pull request merged**
