### PR TITLE
AOSP Oreo

### PR DESCRIPTION
**Pull request by SquaadZulu**
This commit will add the latest build of AOSP Oreo.

### CODE REVIEW

**Comment by SquaadZulu** [comment]
Ah. Well I look forward to the merge when the server gets back up.

**Comment by regalstreak** [comment]
Will be done over a period of 2-3 days. Server is back up

**Review by regalstreak — APPROVED** [review]
As of now latest is r17 so be it

**Comment by SquaadZulu** [comment]
Rodger. Im going to use these sources to make a custom ROM. Just need a device to build for. Degas isn't an option.

**Pull request merged**
