### PR TITLE
Fix brach name check

### PR DESCRIPTION
**Pull request by afaneh92**

### CODE REVIEW

**Comment by regalstreak** [comment]
Would agree on this but @MSF-Jarvis has done something and rebased the repository already :p

**Comment by afaneh92** [comment]
Ok no problem this just an example.

**Comment by regalstreak** [comment]
This was good tho! Btw cm14 sources were up

**Comment by afaneh92** [comment]
Great may I will start new pull request!
AOSP  has restrected and not compiling probably

**Pull request closed without merging**
