### PR TITLE
AOSP 4.4.4

### PR DESCRIPTION
**Pull request by arizaini**
is still work for request? @regalstreak @MSF-Jarvis @DigiGoon

### CODE REVIEW

**Comment by hbashton** [comment]
@arizaini Here= regal = personal

**Comment by arizaini** [comment]
@hbashton sorry, what do you mean?

**Comment by msfjarvis** [comment]
@arizaini nothing, he's an idiot testing out the telegram bot we use to monitor skadoosh

**Comment by arizaini** [comment]
@MSF-Jarvis ok, is still can request some branch?

**Comment by msfjarvis** [comment]
@arizaini requests are closed for now

**Comment by arizaini** [comment]
@MSF-Jarvis why bro?

**Comment by msfjarvis** [comment]
@arizaini no server atm

**Comment by regalstreak** [comment]
@arizaini If you all donate we could do something lol. For now, we don't have a server. Sorry.

**Comment by Grace5921** [comment]
i maybe able to help you in earning by google ad mob  since i my debit card not works online so i can't donate you guys for your great works

**Comment by regalstreak** [comment]
Server and the skadoosh project are live again, please submit again after resolving conflicts. Thanks!

**Pull request closed without merging**
