### PR TITLE
request cm10.2 branch

### PR DESCRIPTION
**Pull request by arizaini**

### CODE REVIEW

**Comment by regalstreak** [comment]
Submit another one in just one commit. This is 3 commits and we do not want to spoil the commit history :)

**Comment by msfjarvis** [comment]
Well squash and merge is a thing @regalstreak ;)

**Comment by msfjarvis** [comment]
But we can't do anything for merge conflicts

**Comment by regalstreak** [comment]
Ik squash and merge but i am on mobile and don't wanna interfere unnecessarily. And there were conflicts. They should learn to do the stuff as they will be compiling ROMs.

**Comment by msfjarvis** [comment]
Well I was to blame for the merge conflict, I got tired so added a note
that https:// needs to be included in the URL.

**Comment by arizaini** [comment]
sorry for noob request like me, but i just want to learn about git and building a ROM, and if i make a mistake only sorry i can said, i still learn from googling and with my many fail trial, and if u deign to guide me about this i very grateful, but if cannot it's ok thanks too, i will request again soon if u authorize my request

**Comment by msfjarvis** [comment]
Make a new pull request first

**Pull request closed without merging**
