### PR TITLE
aosp 2.1_r2.1s

### PR DESCRIPTION
**Pull request by luki122**

### CODE REVIEW

**Comment by aymende7** [comment]
xD seriously?

**Comment by SquaadZulu** [comment]
You seriously want eclair??

**Comment by regalstreak** [comment]
;-;

**Comment by aymende7** [comment]
😂😂😂😂😂

**Comment by SquaadZulu** [comment]
Latest AOSP: 8.0 Oreo

*Makes PR for 2.1 Eclair*

**Comment by regalstreak** [comment]
@luki122 you seriously need this? Because if you don't Ill continue with other sources. Else Ill have to upload this too.

**Pull request closed without merging**
