### PR TITLE
 compress.bash: Fix rom name

### PR DESCRIPTION
**Pull request by afaneh92**

### CODE REVIEW

**Comment by regalstreak** [comment]
OK So wait for more time lol it should be up with the fixed name. I had run outta space

**Comment by afaneh92** [comment]
Im waiting.

**Comment by regalstreak** [comment]
Sorry this time the script had errors. Not corrected them. It is uploading :)

**Comment by regalstreak** [comment]
Done and uploaded

**Comment by afaneh92** [comment]
Thanks, downloading now :)

**Pull request merged**
