### PR TITLE
AICP n7.0 Update compress.bash

### PR DESCRIPTION
**Pull request by tbngw**

### CODE REVIEW

**Comment by ghost** [comment]
@regalstreak wow the repo size is smaller than non-repo. is that really correct or its a mistake ?. i m going to only download the repo file and repo sync it so i will not have to download the large non repo one.and it will save 7gb bandwidth.

**Comment by regalstreak** [comment]
Well you can try. I don't really know as the source was in a mess at this point of time.

**Comment by ghost** [comment]
@regalstreak the repo is corrupted. i checked the md5 and its same so its 100% a corrupted archive.

**Comment by ghost** [comment]
@regalstreak  here is aicp repo if u want u can import it to the skadoos  aicp dir
https://www.androidfilehost.com/?fid=24694152805485245
(29GB)

**Pull request merged**
