### PR TITLE
DU update compress.bash

### PR DESCRIPTION
**Pull request by TheHercules**

### CODE REVIEW

**Comment by msfjarvis** [comment]
@TheHercules You've told something. Keeping these open won't help

**Comment by TheHercules** [comment]
@MSF-Jarvis okay. i thought you'd do it when your server gets fixed. 
( just send in a text, when your server gets alright,( if u could), I'll only PR more after u say so)

**Comment by msfjarvis** [comment]
You didn't specify the branch name here, do that then I'll merge. For unofficial devices you'd probably need the `m-caf` branch

**Comment by regalstreak** [comment]
Server and the skadoosh project are live again, please submit again after resolving conflicts. Thanks!

**Pull request closed without merging**
