### PR TITLE
Exodus 6.0

### PR DESCRIPTION
**Pull request by msfjarvis**
Just testing a CLI client that lets you create PRs from the command line, ignore if server resources are scanty

### CODE REVIEW

**Comment by regalstreak** [comment]
Just tell me the name of the client

**Comment by msfjarvis** [comment]
#secret :wink:

**Comment by regalstreak** [comment]
Anyway, no exodus for you.,
I have to fix some stuff of the repo and norepo thing and have to check compress 2 roms now by quinchang or whoever that is

**Comment by msfjarvis** [comment]
As if I was even going to build anything lol :stuck_out_tongue_winking_eye:

**Comment by regalstreak** [comment]
I know you dont build shiz

**Pull request closed without merging**
