### PR TITLE
DU n7x

### PR DESCRIPTION
**Pull request by ashutoshbsathe**
Dirty Unicorns Nougat

### CODE REVIEW

**Comment by regalstreak** [comment]
Suggest me a place to upload man :(

**Comment by ashutoshbsathe** [comment]
Mega seems fine ?

**Comment by ashutoshbsathe** [comment]
Just read your comment about mega .
Split archives on afh also seems a good option for me

**Comment by locxFIN** [comment]
@Ashutosh-01 I just realized that this was your trap

**Comment by ashutoshbsathe** [comment]
Did I do something wrong ?

**Comment by regalstreak** [comment]
Ill write the function tomorrow. Doing a lot of stuff lol. Not getting time for skadoosh. Remind me tomorrow afternoon. @Ashutosh-01 

Btw that might be a troll

**Comment by regalstreak** [comment]
@Ashutosh-01 Submit new pr, new branch
Have written the stuff needed

**Comment by locxFIN** [comment]
@Ashutosh-01 I'm sorry, I don't know what happened, but I have to tell you this. I sent that message to my friend on Telegram and something went wrong with GitHub bot. For some reason it sent the same message to a completely random pull request 😆 I just couldn't stop laughing when I noticed what that looked like "this was your trap" hahaha

**Pull request closed without merging**
