### PR TITLE
AOSPExtended

### PR DESCRIPTION
**Pull request by nikhilpal2705**

### CODE REVIEW

**Comment by regalstreak** [comment]
Why deleted?

**Comment by nikhilpal2705** [comment]
forgot to remove .git from the manifest link.
sorry i'm noob.

**Comment by regalstreak** [comment]
Lol .git doesn't matter. It's the dame

**Comment by regalstreak** [comment]
same*

**Comment by nikhilpal2705** [comment]
ok reopend

**Review by regalstreak — APPROVED** [review]

**Comment by nikhilpal2705** [comment]
Thanks Sir

**Pull request merged**
