### PR TITLE
Update compress.bash

### PR DESCRIPTION
**Pull request by chachinito**
RR 2017

### CODE REVIEW

**Comment by regalstreak** [comment]
All is good but can you suggest me a place I can upload? Afh is not allowing files greater than 6 gb :(

**Comment by ashutoshbsathe** [comment]
@regalstreak how about mega ?

**Comment by regalstreak** [comment]
Mega is good but only 50 gig. Would only be able to do a few sources. Ill maybe write something for breaking the archives into sizes of 6gig so afh it could be

**Comment by RishuP** [comment]
@Ashutosh-01 Fcuk si gonig on ?

**Comment by ashutoshbsathe** [comment]
@RishuP what did I do ? :P

**Comment by regalstreak** [comment]
Anything but congrats on getting into coep tho. We're struggling in local colleges :(

**Comment by regalstreak** [comment]
@regalstreak @MSFJarvis :( coep is in top 100 colleges for cs

**Comment by regalstreak** [comment]
@chachinito Submit new pr, new branch
Have written the stuff needed

**Pull request closed without merging**
