### PR TITLE
Update compress.bash

### PR DESCRIPTION
**Pull request by NazarMohamed**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Stupid mistakes, you shouldn't even think of building ROMs.

**Comment by xdevs23** [comment]
1:
http instead of https
2:
GitHub instead of github (good that he knows that you can do that)
3:
Kek

**Comment by msfjarvis** [comment]
@xdevs23 Someone also tell him the name of the ROM is PureNexus and not pure.  Also the moronic manifest link

**Comment by regalstreak** [comment]
Calm down. You can just tell him.

**Comment by msfjarvis** [comment]
@regalstreak Sorry, patience exhausted with these morons.

**Comment by regalstreak** [comment]
I don't want hatred in here. Please. Just close the stuff.

**Comment by msfjarvis** [comment]
@regalstreak Already did

**Comment by regalstreak** [comment]
@MSF-Jarvis Yes

**Pull request closed without merging**
