### PR TITLE
Add AOSB

### PR DESCRIPTION
**Pull request by Qiangong2**
because MSF Jarvis wants more than just "Update compress.bash" :P

### CODE REVIEW

**Comment by msfjarvis** [comment]
Well regalstreak can do that while doing the squashed merge but he's just
lazy :p skadoosh is currently broken so no PRs will be merged. When it's
fixed I'll clear out the backlog and merge this in.

**Comment by Qiangong2** [comment]
So LuneOS is not being compressed yet?

**Comment by msfjarvis** [comment]
If we include this PR we're currently four ROMs behind I guess, let me
confirm about LuneOS

**Comment by msfjarvis** [comment]
Yeah, no LuneOS, I'm so sorry about that, give us some time and it'll be
fixed

**Comment by Qiangong2** [comment]
okay

**Pull request closed without merging**
