### PR TITLE
LineageOS 13.0

### PR DESCRIPTION
**Pull request by DarwishCodes**

### CODE REVIEW

**Review by regalstreak — APPROVED** [review]
All is good. Approved 👍

**Comment by DarwishCodes** [comment]
Awesome!
Really awesome work in this script sir.
Keep it up.

**Comment by regalstreak** [comment]
Thanks 💃

**Comment by regalstreak** [comment]
Done. Check sourceforge folder @XxDishoxX

**Comment by DarwishCodes** [comment]
Wow, i gotta admit
That was fast. 🥇 
Thanks again

**Comment by regalstreak** [comment]
😁

**Pull request merged**
