### PR TITLE
CyanogenMod staging/cm-14.0    

### PR DESCRIPTION
**Pull request by afaneh92**

### CODE REVIEW

**Comment by regalstreak** [comment]
ok after the recent changes to the manifest (which were just pushed) it syncs. Will be up shortly

**Comment by regalstreak** [comment]
``` shell
ROM Sync Completed Successfully
mkdir: cannot create directory ‘CyanogenMod-staging/cm-14.0-no-repo-20160906’: No such file or directory
mv: target 'CyanogenMod-staging/cm-14.0-no-repo-20160906' is not a directory
Separating Failed
```

Lol seriously?

**Comment by afaneh92** [comment]
Does the " / " affect to the rom directory!!

**Comment by regalstreak** [comment]
haha yeah. Unix cant have / in a directory. Ill have to add this as a check in the script

**Comment by afaneh92** [comment]
Can you rename it without redo every thing?

**Comment by regalstreak** [comment]
yes i have done it currently. Ill come up with a cleaner solution tomorrow

**Comment by ghost** [comment]
Why repo is not uploaded?

**Comment by afaneh92** [comment]
I will add new pull request for repo 
The current no repo missing things

**Comment by regalstreak** [comment]
> Why repo is not uploaded?

Dont know. Will do later. submit up a pr

**Pull request merged**
