### PR TITLE
tesla os

### PR DESCRIPTION
**Pull request by Qiangong2**

### CODE REVIEW

**Comment by regalstreak** [comment]
You gone mad or something? How the fuck will you compile all these?

**Comment by Qiangong2** [comment]
With two computers. :) each one has 16gb of RAM and 256gb ssd

**Comment by Qiangong2** [comment]
I'm still syncing other sources myself

**Comment by regalstreak** [comment]
Woah!!

**Comment by msfjarvis** [comment]
@regalstreak, not everyone needs to lie to parents to pursue his Android
hobby/passion :(

**Comment by Qiangong2** [comment]
I have school most of the week, so I start compilation on one computer and syncing on another in the morning, at lunch, after compilation is finished, I compile a different ROM. If syncing is done, I sync another ROM.

**Comment by Qiangong2** [comment]
Also, does slimbean 4.2 support dual sim? I'm syncing that now.

**Pull request merged**
