### PR TITLE
cm-10.2

### PR DESCRIPTION
**Pull request by arizaini**

### CODE REVIEW

**Comment by arizaini** [comment]
thanks

**Comment by msfjarvis** [comment]
Curious....upload failed. Redoing it, will need to add error checking, the cleanup kicked in even without a successful upload coz it's dumb currently.  @regalstreak, @FireLord1 has error checks in his build-script, please kang it for us :laughing:

**Comment by regalstreak** [comment]
Sure tomorrow

Get Outlook for Android

On Sat, Aug 6, 2016 at 12:49 AM +0530, "Harsh Shandilya" notifications@github.com wrote:

Curious....upload failed. Redoing it, will need to add error checking, the cleanup kicked in even without a successful upload coz it's dumb currently.  @regalstreak, @FireLord1 has error checks in his build-script, please kang it for us 😆

**Comment by regalstreak** [comment]
You have a mail server set up on the server? We will send mails to you and me. Else we just email root.

**Comment by msfjarvis** [comment]
Not yet, but doable. I'm guessing I can do something about it tomorrow.

**Comment by regalstreak** [comment]
Hmm, well this is the shiz i coded right now 
https://github.com/regalstreak/skadoosh/commit/e95cf1d7a415031c3c0407a4cc36b621d31194f9
There may be derps ik
But well, lets check

**Comment by arizaini** [comment]
is any problem with my request branch sir?
i didn't see cm10.2 on here https://www.androidfilehost.com/?w=files&flid=87182

**Comment by msfjarvis** [comment]
It's synced and uploaded, just haven't imported it yet I guess, will do it
soon.

**Comment by arizaini** [comment]
@MSF-Jarvis thanks before, but if u didn't objections can u upload repo folder too cause i need that, thanks

**Comment by msfjarvis** [comment]
I had uploaded that, a bug in AFH caused it to be nuked. I'll try and get
that up tonight.

**Comment by arizaini** [comment]
thanks, i'll waiting for that

**Comment by arizaini** [comment]
@MSF-Jarvis sorry before, how long do i have to wait sir?
i really need that too, thanks

**Comment by msfjarvis** [comment]
I'm doing it right now, but.... cm10.2 in 2016? Seriously?

**Comment by arizaini** [comment]
i'm still learn for developing, so i started from 4.3 cause my phone running 4.3 latest version, my phone doesn't have any develop and i can't push out to 4.4 or 6.0, i'm doing it step by step, so i request cm-10.2(4.3) android version, i u can help me up for cm-10.2 with repo folder, I am very grateful for who work behind this project branch

**Comment by arizaini** [comment]
@MSF-Jarvis thanks :+1:

**Pull request merged**
