### PR TITLE
AOSP 7.1.1 Release 6

### PR DESCRIPTION
**Pull request by renanmarcos**

### CODE REVIEW

**Comment by renanmarcos** [comment]
@MSF-Jarvis The server is up again? If yes, can you merge this request please? :)

**Comment by msfjarvis** [comment]
Will merge this after #92 finishes

**Comment by renanmarcos** [comment]
Thanks ^^

**Comment by regalstreak** [comment]
Server and the skadoosh project are live again, please submit again after resolving conflicts. Thanks!

**Pull request closed without merging**
