### PR TITLE
request for AOSP 4.4.4_r2.0.1

### PR DESCRIPTION
**Pull request by androidlover5842**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Looks like Krieger didn't kick in after this commit, so this hasn't been uploaded and the next commit is being worked on. Sorry about this, I'll run a build manually when FlareROM is done

**Comment by androidlover5842** [comment]
it's okay Good Luck

**Comment by androidlover5842** [comment]
it's didn't uploaded yet :( https://www.androidfilehost.com/?w=files&flid=87214

**Comment by msfjarvis** [comment]
Yeah, won't be uploaded. I'm closing this service for now, requesting @regalstreak and @DigiGoon to pitch in with their own servers for the time being

**Pull request merged**
