### PR TITLE
Add checks for slashes in branch, remove whitespaces

### PR DESCRIPTION
**Pull request by msfjarvis**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Better version of #40

**Comment by regalstreak** [comment]
Agree. Will merge.

**Comment by afaneh92** [comment]
That clear but we still need original branch name when sync the repo

**Comment by msfjarvis** [comment]
I don't think `staging-cm-14.0` is too different from `staging/cm-14.0`
that people won't know they're the same.

**Comment by regalstreak** [comment]
It's alright @mohammad92. Won't make much of a difference

**Comment by afaneh92** [comment]
I mean in 
repo init -u $LINK -b $BRANCH
We need `staging/cm-14.0` not `staging-cm-14.0`
Other wise it will fail!!

**Comment by msfjarvis** [comment]
So I guess we'll move this check into `skadoo.sh`

**Comment by afaneh92** [comment]
No need
Just leave BRANCH for repo
And new variable like BRANCHDIR for mkdir

**Comment by afaneh92** [comment]
I will make new pull request when Im at home

**Comment by regalstreak** [comment]
Hmm yeah he is right.
Well just hook up branchtest lile that
And rename the $branch to $branchtest in the separatestuff() and other functions.

**Pull request merged**
