### PR TITLE
Replace slash with dash in branch name if exist

### PR DESCRIPTION
**Pull request by afaneh92**

### CODE REVIEW

**Comment by msfjarvis** [comment]
I don't see any use case for this, maybe a few sample file names would make it clearer?

**Comment by regalstreak** [comment]
Abeyy this is very useful. Branch names like staging/cm-14.0 can't be made into a dir as unix won't take / in  a dir. I didn't merge yet cuz i had slept. I'll merge later after testing

**Comment by msfjarvis** [comment]
😒 I have a cleaner pull request open

**Comment by msfjarvis** [comment]
For this very issue

**Comment by regalstreak** [comment]
Ye looked up. That looks better.
So btw why don't you download
https://play.google.com/store/apps/details?id=com.gh4a
Is better than email

**Comment by msfjarvis** [comment]
I use Inbox by Google because I like the grouping and bundling, especially
for GitHub mails.

**Comment by regalstreak** [comment]
You can't merge with inbox

**Pull request closed without merging**
