### PR TITLE
Update compress.bash

### PR DESCRIPTION
**Pull request by vishal-roy**

### CODE REVIEW

**Comment by vishal-roy** [comment]
Hello, I want to ask if we can compress kernal sources

**Comment by regalstreak** [comment]
Well I don't think kernel sources would work. I'll have to add support but I ain't doing that for now. Maybe the coming week I can write it for you

**Comment by vishal-roy** [comment]
Thanks you and will be waiting for kernal support

**Comment by regalstreak** [comment]
@rohandebroy Sure

**Comment by vishal-roy** [comment]
@regalstreak hello, have i done something wrong coz in the source forge site the source file is only 3.3 mb 
here plz check https://sourceforge.net/projects/skadoosh/files/VertexOS/Vertex-7.1/

**Comment by regalstreak** [comment]
You fucked up. There is no Vertexos-7.1 branch.

**Comment by vishal-roy** [comment]
There used to be one they shifted and I am going for another pull request with correct branch and plz delete the files from source forge and Sorry

😭

**Pull request merged**
