### PR TITLE
Update compress.bash

### PR DESCRIPTION
**Pull request by vishal-roy**
Hey bro sorry plz Marge this and delete the files uploaded on source forge plz

### CODE REVIEW

**Comment by vishal-roy** [comment]
Plz check if I have not done any mistake on compress.bash file

**Comment by vishal-roy** [comment]
@regalstreak bro plz marge

**Comment by regalstreak** [comment]
*merge and not marge

**Comment by vishal-roy** [comment]
Sorry didn't notice

**Pull request merged**
