### PR TITLE
 AOSP 7.0.0_r1 no repo

### PR DESCRIPTION
**Pull request by afaneh92**

### CODE REVIEW

**Comment by regalstreak** [comment]
It is being compressed :) Remind me in some hours to pull it to afh

**Comment by afaneh92** [comment]
Ok thanks :+1:

**Comment by regalstreak** [comment]
Well you didnt change the rom name lol. wanna do it again? xD

**Comment by regalstreak** [comment]
let it be for this time

**Comment by afaneh92** [comment]
Sorry I didn't notice you add the name but you can rename it from AFH

**Comment by regalstreak** [comment]
yes

**Comment by afaneh92** [comment]
Did not find it, you removed it?

**Pull request merged**
