### PR TITLE
AOSB kk

### PR DESCRIPTION
**Pull request by Qiangong2**
aosb

### CODE REVIEW

**Comment by regalstreak** [comment]
Please name your pull requests

**Comment by msfjarvis** [comment]
Squash and Merge button lets you edit the commit message @regalstreak

**Comment by regalstreak** [comment]
Why the fuck you merged now 2 compressions in parallel i guess the server
will die of exhaustion

**Comment by msfjarvis** [comment]
@regalstreak krieger did 4 compressions in parallel and none failed. Not to mention three non-ccache clean builds in parallel didn't kill it too. Chill, machines don't get exhausted

**Comment by regalstreak** [comment]
Is my thing called krieger? Is my thing dedicated?

**Comment by msfjarvis** [comment]
Stop whining

**Comment by regalstreak** [comment]
Switch on your server. Start compressing

**Comment by msfjarvis** [comment]
There is a subtle difference between "off" and "terminated"

**Comment by regalstreak** [comment]
You never told me that it got terminated 🙄
I feel sad for you.
Jaake padhai karo fir.
💯 laane hai bhai ko.

**Comment by regalstreak** [comment]
@Qiangong2 currently going on

**Comment by regalstreak** [comment]
@Qiangong2 

``` shell
Fetching projects:  99% (455/459)  chromium_org/third_party/eyesf
Password for 'https://github.com': 

Password for 'https://github.com': remote: Repository unavailable due to DMCA takedown.
remote: See the takedown notice for more details:
remote:   https://github.com/github/dmca/blob/master/2014/2014-12-22-Cambridge-Mobile.md.
fatal: Authentication failed for 'https://github.com/CyanogenMod/android_external_svox/'

remote: Repository not found.
fatal: Authentication failed for 'https://github.com/cyngn/android_vendor_cyngn/'
```

Not going to fix sorry :package:

**Pull request merged**
