### PR TITLE
ResurrectionRemix-5.7.2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by msfjarvis** [comment]
@FaArIsH the sources have been uploaded, please import them @regalstreak

**Comment by regalstreak** [comment]
Yes wait

**Comment by ghost** [comment]
@MSF-Jarvis can u update it ? i want to download both repo and non repo and then everyday do repo sync  ( now i have only non repo and if i download the repo which is a month old now so repo sync will take long,)

**Comment by msfjarvis** [comment]
I can't update it anymore

**Pull request merged**
