### PR TITLE
ColorOS

### PR DESCRIPTION
**Pull request by Qiangong2**
I have the patchrom on mine because the ColorOS repo doesn't work, but people have already copied the source before on github.

### CODE REVIEW

**Comment by msfjarvis** [comment]
@Qiangong2 Well the "default.xml" in the URL is raising some alarms in my head

**Comment by Qiangong2** [comment]
look at the file

**Comment by Qiangong2** [comment]
it's just a manifest

**Comment by msfjarvis** [comment]
@Qiangong2 URL dude, repo init isn't supposed to have such a URL. You init the repo, not the file.

**Comment by Qiangong2** [comment]
it is the repo

**Comment by Qiangong2** [comment]
it's like cyanogenmod/android.git

**Comment by msfjarvis** [comment]
Damn I've been screaming at the wrong PR

**Comment by Qiangong2** [comment]
nevermind revert

**Comment by Qiangong2** [comment]
you were right

**Comment by Qiangong2** [comment]
should be just patchrom

**Comment by msfjarvis** [comment]
@Qiangong2 It's not building anytime soon, servers are down.

**Comment by Qiangong2** [comment]
okay, i'll create a new pull request

**Pull request merged**
